sudo: required
dist: trusty

language: java

before_install:
      - openssl aes-256-cbc -K $encrypted_2760b77333f5_key -iv $encrypted_2760b77333f5_iv -in secrets.tar.enc -out secrets.tar -d
      - tar xvf secrets.tar
      - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
      - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
      - gpg -a --export E084DAB9 | sudo apt-key add -
      - sudo apt-get -qq update
      - sudo apt-get -qq -y install r-base
      - sudo R CMD javareconf

